name: OCPL Configuration Management Standards Check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

#cancel previous runs for this ref
concurrency:
  group: ${{ github.ref }}-cm-standards
  cancel-in-progress: true

jobs:
  commitlint_remote:
    uses: nciocpl/.github/.github/workflows/ocpl_cm_standards_check.yml@workflow/v1
