name: Test Backstop
on:
  push:
    branches:
      - master
      - main
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
      - 'prototype/**'
    tags:
      - '*'
  pull_request:

defaults:
  run:
    working-directory: app


jobs:
  build:
    name: Test Site
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      ## Checkout the code
      - name: Checkout branch
        uses: actions/checkout@v3

      ## Setup node and npm caching
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com
          scope: "@nciocpl"
      - name: Run NPM
        run: npm install

      ## Serve the site to test it
      - name: Test Site
        run: npm run backstop-test
        env:
          BACKSTOP_BASE_URL: http://localhost:8080

      ## Upload failed css tests
      - uses: actions/upload-artifact@v2
        name: Upload failed tests
        if: failure()
        with:
          name: failed-backstopjs
          path: backstop_data

      ## Upload successful css tests
      - uses: actions/upload-artifact@v2
        name: Upload successful tests
        with:
          name: success-backstopjs
          path: backstop_data/bitmaps_test/**/report.json
