name: Test Backstop
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths: app/**

#cancel previous runs for this ref
concurrency:
  group: ${{ github.ref }}-test-backstop
  cancel-in-progress: true

defaults:
  run:
    working-directory: app

jobs:
  backstop:
    name: Test Site
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ !github.event.pull_request.draft }}
    steps:
      ## Checkout the code
      - name: Checkout branch
        uses: actions/checkout@v3

      ## Setup node and npm caching
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "app/.nvmrc"
          registry-url: https://npm.pkg.github.com
          scope: "@nciocpl"
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Run NPM
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ## Serve the site to test it
      - name: Test Site
        run: npm run start & sleep 10 && npm run backstop-test
        continue-on-error: true
        env:
          BACKSTOP_BASE_URL: http://localhost:8080

      ## Upload failed css tests
      - uses: actions/upload-artifact@v3
        name: Upload failed tests
        if: failure()
        with:
          name: failed-backstopjs
          path: app/backstop_data

      ## Upload successful css tests
      - uses: actions/upload-artifact@v3
        name: Upload successful tests
        with:
          name: success-backstopjs
          path: app/backstop_data/bitmaps_test/**/report.json

  approve:
    name: Approve Tests
    runs-on: ubuntu-latest
    needs: backstop
    if: ${{ needs.backstop.result == 'failure' }}
    environment: QA-Approval
    steps:
      - name: Wait for Approval
        run: echo "QA Approved"

